### ISSUE TITLE
Graph glitches with high GPU usage

### ISSUE THREAD

**Issue by feikname** [projectfluent/arewefluentyet.com#10]
**Steps to reproduce:**
Hover your mouse over the graph from left to right and right to left repeatedly until the following happens:
![image](https://user-images.githubusercontent.com/4926869/64474027-a18f1180-d144-11e9-87d3-373ee0736be7.png)
(takes a few seconds)

Tested on Firefox 69.0, Windows 10 1903 with Intel UDH Graphics 620 igfx

**Comment by zbraniecki** [comment]
Mhm, I noticed it, but I'm not sure how to fix it. My best guess is that it happens when we paint on canvas and the hover changes and we start painting again in a different place but the previous paint continues and somehow that gets in a loop.

I don't have any experience debugging canvas/GPU :(

**Comment by serak** [comment]
i have checked and this issue is only firefox. i think it might be bug in FF Chrome does not have this problem

**Comment by zbraniecki** [comment]
Updated to Chart.js 2.9.0 and datalabels plugin 0.7.0, but that didn't help.

Reported as https://bugzilla.mozilla.org/show_bug.cgi?id=1591634

**Comment by eemeli** [comment]
This is fixed in commit a80eb70.
