### ISSUE TITLE
Consider building a celebratory screen for Milestone completion

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/arewefluentyet.com#16]
As we get close to 100% of M1, it might be nice to add some celebration to the screen when the milestone is completed!

@nordzilla - thoughts? :)

**Comment by nordzilla** [comment]
This sounds like a good idea to me. 

What do you have in mind? Something simple like a little :tada: emoji next to it?

**Comment by zbraniecki** [comment]
No idea! :) Just an impulse!

**Comment by mikeconley** [comment]
Could also do something similar to what arewexblstill.com did for reaching 0.

See https://github.com/bgrins/xbl-analysis/commit/8d2273e5d3035901e75acbc073d4c2e5e98306c5 and https://github.com/bgrins/xbl-analysis/commit/c01f1f381e8dcd4f6434baeb443b232ea765bd87.

Specifically, upon reaching 0, it looks like [some confetti](https://github.com/Agezao/confetti-js) got thrown.

**Comment by kpatenio** [comment]
Already discussed this with @nordzilla, but I'd be happy to give this a go!

**Comment by Rexogamer** [comment]
This seems to have been completed?

**Comment by nordzilla** [comment]
@Rexogamer 

Yes, this has been completed. 

My apologies, I didn't realize that this issue never got marked as resolved.
