### ISSUE TITLE
Possible data issue? (05/07/2020, M2)

### ISSUE THREAD

**Issue by Rexogamer** [projectfluent/arewefluentyet.com#20]
It seems as though [this value](https://github.com/projectfluent/arewefluentyet.com/blob/f253b16f3fe1bb205d24bc4cb5f6e7a34bdf497c/data/M2/progress.json#L402) is wrong? It's a pretty sudden dip, whereas 293 would seem more likely (although it may genuinely be 93)

**Comment by eemeli** [comment]
Quite likely, yes. Probably something odd happened during that startup so only a fraction of the strings were loaded, or registered.

**Comment by eemeli** [comment]
Closing as WONTFIX, as we're no longer updating the M2 milestone.
