### ISSUE TITLE
Proposal: drop M1, M2 and automate data generation

### ISSUE THREAD

**Issue by flodolo** [projectfluent/arewefluentyet.com#22]
CC @eemeli @nordzilla 

Chatting with Eemeli, we were wondering if it's time to only keep M3 at this point.

- M1 has been completed for a while
- M2 doesn't seem very relevant, after we dropped all DTDs? It's also incredibly complicated to generate, and data doesn't seem as reliable (time zone, potentially platform dependent?).

Not exactly sure how that would look like: should we keep around the scripts and JSON data, but only update M3 data, so that the graphs are still available/visible, and set M3 as the default view?

If we only keep M3, then it should be easy to generate the data via GitHub workflow once a week.

**Comment by eemeli** [comment]
This is now done, with #24 adding the M3 automation and [this commit](https://github.com/projectfluent/arewefluentyet.com/commit/b8a130b2358f30f50455adca6e6d67a17f0a2de4) dropping the M1 and M2 milestones from the UI. They're still reachable via their URLs, but those URLs aren't linked to from the site anymore.
