### ISSUE TITLE
Make aggregator resiliant against local paths

### ISSUE THREAD

**Issue by Pike** [projectfluent/arewefluentyet.com#8]
I found why the current data has artifacts from the local setup in it.

The "." isn't actually `cwd` in the mozpath logic. We should substitute that for absolute paths, probably cwd proper.

@zbraniecki, would you want to take that as a ride-along?

**Comment by zbraniecki** [comment]
You mean the `../../mozilla-unified/en-US/devtools/client/dom.properties` vs `en-US/devtools/client/dom.properties` ?

Should the path be `devtools/client/dom.properties`?

**Comment by Pike** [comment]
> You mean the `../../mozilla-unified/en-US/devtools/client/dom.properties` vs `en-US/devtools/client/dom.properties` ?

Yeah.

> Should the path be `devtools/client/dom.properties`?

That could work, too, but that's probably harder to do w/out a deep dive into assumptions on how our files are structured?

**Comment by zbraniecki** [comment]
Hmm, I took a look, and I'm not sure where the change has to be placed. Can you provide a pointer for me to start @Pike?

**Comment by zbraniecki** [comment]
I think I got it.

**Comment by zbraniecki** [comment]
Fixed in https://github.com/projectfluent/arewefluentyet.com/commit/6065fef18c65a5ce3150310360a39fe05894cd64
